### ISSUE TITLE
Authorization issue when trying to upload my package.

### ISSUE THREAD

**Issue by linxuedong** [linxuedong/django-core#1]
## Context
###unable to authenticate with correct credentials

I can login https://pypi.python.org/pypi with my username password so I am sure they are correct

But I cannot upload my package. I always get
```
Upload failed (403): Invalid or non-existent authentication information.
error: Upload failed (403): Invalid or non-existent authentication information.
```

## REF
https://github.com/pypa/pypi-legacy/issues/590
https://packaging.python.org/tutorials/distributing-packages/

**Comment by idisblueflash** [comment]
配置：https://packaging.python.org/tutorials/distributing-packages/#id76
注意：检查密码是否正确
